sed '/COTAHIST/d' *.TXT -i
sed 's/.\{2\}/&;/' *.TXT -i
sed 's/.\{11\}/&;/' *.TXT -i
sed 's/.\{14\}/&;/' *.TXT -i
sed 's/.\{27\}/&;/' *.TXT -i
sed 's/.\{31\}/&;/' *.TXT -i
sed 's/.\{44\}/&;/' *.TXT -i
sed 's/.\{55\}/&;/' *.TXT -i
sed 's/.\{59\}/&;/' *.TXT -i
sed 's/.\{64\}/&;/' *.TXT -i
sed 's/.\{78\}/&;/' *.TXT -i
sed 's/.\{92\}/&;/' *.TXT -i
sed 's/.\{106\}/&;/' *.TXT -i
sed 's/.\{120\}/&;/' *.TXT -i
sed 's/.\{134\}/&;/' *.TXT -i
sed 's/.\{148\}/&;/' *.TXT -i
sed 's/.\{162\}/&;/' *.TXT -i
sed 's/.\{168\}/&;/' *.TXT -i
sed 's/.\{187\}/&;/' *.TXT -i
sed 's/.\{206\}/&;/' *.TXT -i
sed 's/.\{220\}/&;/' *.TXT -i
sed 's/.\{222\}/&;/' *.TXT -i
sed 's/.\{231\}/&;/' *.TXT -i
sed 's/.\{252\}/&;/' *.TXT -i
sed 's/.\{265\}/&;/' *.TXT -i
sed 's/.\{76\}/&./' *.TXT -i
sed 's/.\{91\}/&./' *.TXT -i
sed 's/.\{106\}/&./' *.TXT -i
sed 's/.\{121\}/&./' *.TXT -i
sed 's/.\{136\}/&./' *.TXT -i
sed 's/.\{151\}/&./' *.TXT -i
sed 's/.\{166\}/&./' *.TXT -i
sed 's/.\{173\}/&./' *.TXT -i
sed 's/.\{226\}/&./' *.TXT -i
sed 's/.\{7\}/&-/' *.TXT -i
sed 's/.\{10\}/&-/' *.TXT -i
sed 's/.\{238\}/&-/' *.TXT -i
sed 's/.\{241\}/&-/' *.TXT -i
sed 's/R$  ;//g' *.TXT -i
cat *.TXT >> consolidado.csv
